

# https://github.com/AkkeSun/securityOauth2/blob/master/src/main/java/com/example/securityoauth2/config/AuthServerConfig.java
# https://github.com/marcosbarbero/spring-boot2-oauth2-jwt
# https://gaemi606.tistory.com/entry/Spring-Boot-Spring-Security-OAuth2
server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://root@localhost:3306/local_test?serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl