server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        ######### Client Setting #########
        registration:
          spring:
            authorization-grant-type: password
            client-id: oauth2-test
            client-name: oauth2-test
            client-secret: pass
            client-authentication-method: client_secret_basic
            scope: read,write
            provider: spring
          google:
            client-id: 303918678932-4b0hug1rf226dpj022jkl083nkv7q0d5.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email
          naver:
            client-id: UwwvxdTjzLLCa1Zc4nYV
            client-secret: YCkpwJuRd5
            scope: profile,email
            authorization-grant-type: authorization_code
            client-name: naver-client-app
            redirect-uri: http://localhost:8081/login/oauth2/code/naver
          kakao:
            client-id: 6aca63e773a28e941f590d65893fa900 # REST API Key
            client-secret: QRGYmnewrcK8WAA3eeCQ4qSOFpP2Kyvt
            scope: profile_nickname, profile_image, account_email
            authorization-grant-type: authorization_code
            client-name: client-app
            redirect-uri: http://localhost:8081/login/oauth2/code/kakao

        ######### Auth Server Setting #########
        provider:
          spring:
            authorization-uri: http://localhost:9000/oauth/authorize
            token-uri: http://localhost:9000/oauth/token
            # 토큰 디코딩 경로
            user-info-uri: http://localhost:9000/userinfo
            # 토큰 디코딩 시 사용자 이름 컬럼명
            user-name-attribute: user_name
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            issuer-uri: https://kauth.kakao.com
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            jwk-set-uri: https://kauth.kakao.com/./well-known/jwks.json
            user-name-attribute: id